# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_auto_20180704_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
